# Generated by Django 5.2 on 2025-04-18 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.users')),
                ('grade_level', models.CharField(max_length=20)),
                ('strand', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.users')),
                ('department', models.CharField(max_length=50)),
                ('subjects', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
