# Generated by Django 5.2 on 2025-04-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='pfp_url',
            field=models.TextField(default='https://ssl.gstatic.com/accounts/ui/avatar_2x.png'),
        ),
        migrations.AddField(
            model_name='users',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='strand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
