# Generated by Django 5.2 on 2025-04-19 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_users_bio_users_grade_users_pfp_url_users_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='users',
            name='section',
        ),
        migrations.RemoveField(
            model_name='users',
            name='strand',
        ),
    ]
