# Generated by Django 5.2 on 2025-04-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_users_grade_remove_users_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
