# Generated by Django 5.2 on 2025-04-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_teachers_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='subjects',
            new_name='sections',
        ),
        migrations.RemoveField(
            model_name='students',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='users',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='users',
            name='pfp_url',
        ),
        migrations.AddField(
            model_name='users',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
